#!/bin/bash
set -eu

/init_nullmailer

# Start supporting services
service nginx start
service php5-fpm start

# if the mount dirs are empty, populate them from the source
[ "$(ls -A /srv/limesurvey/tmp)" ] || rsync -a /root/limesurvey/tmp/ /srv/limesurvey/tmp/
[ "$(ls -A /srv/limesurvey/upload)" ] || rsync -a /root/limesurvey/upload/ /srv/limesurvey/upload/
[ "$(ls -A /srv/limesurvey/application/config)" ] || rsync -a /root/limesurvey/application/config/ /srv/limesurvey/application/config/

# set limesurvey writable directories


tail -f /var/log/php-fpm.log